package com.emc.fapi.jaxws.v4_3_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "monitoredParameterType")
@XmlEnum
public enum MonitoredParameterType {
    NUMBER_OF_GROUPS("NUMBER_OF_GROUPS"),
    NUMBER_OF_TRANSFERRING_GROUPS("NUMBER_OF_TRANSFERRING_GROUPS"),
    NUMBER_OF_REPLICATING_SETS("NUMBER_OF_REPLICATING_SETS"),
    NUMBER_OF_SPLITTING_HOSTS("NUMBER_OF_SPLITTING_HOSTS"),
    NUMBER_OF_CLARIION_HOSTS("NUMBER_OF_CLARIION_HOSTS"),
    DAYS_LICENSE_LEFT("DAYS_LICENSE_LEFT"),
    LOCAL_REPLICATED_ARRAY("LOCAL_REPLICATED_ARRAY"),
    REMOTE_REPLICATED_ARRAY("REMOTE_REPLICATED_ARRAY"),
    LOCAL_REPLICATED_CLUSTER("LOCAL_REPLICATED_CLUSTER"),
    REMOTE_REPLICATED_CLUSTER("REMOTE_REPLICATED_CLUSTER"),
    NUMBER_OF_GRID_GROUPS("NUMBER_OF_GRID_GROUPS"),
    LAG_TRANSACTION("LAG_TRANSACTION"),
    LAG_TIME("LAG_TIME"),
    LAG_DATA("LAG_DATA"),
    PAUSE_JOURNAL_TSP_USAGE("PAUSE_JOURNAL_TSP_USAGE"),
    PAUSE_VIRTUAL_MEMORY_USAGE("PAUSE_VIRTUAL_MEMORY_USAGE"),
    NUMBER_OF_SPLITTER_CLUSTERS("NUMBER_OF_SPLITTER_CLUSTERS"),
    TOTAL_NUMBER_OF_SPLITTER_LUNS("TOTAL_NUMBER_OF_SPLITTER_LUNS"),
    SYMMETRIX_PROTECTED_VOLUMES("SYMMETRIX_PROTECTED_VOLUMES"),
    NUMBER_OF_VPLEX_HOSTS("NUMBER_OF_VPLEX_HOSTS"),
    NUMBER_OF_VPLEX_DIRECTORS("NUMBER_OF_VPLEX_DIRECTORS"),
    NUMBER_OF_SYMMETRIX_HOSTS("NUMBER_OF_SYMMETRIX_HOSTS"),
    SYMMETRIX_SESSIONS("SYMMETRIX_SESSIONS"),
    NUMBER_OF_WLPS("NUMBER_OF_WLPS"),
    NUMBER_OF_GUIDS("NUMBER_OF_GUIDS"),
    NUMBER_OF_ESX_CLUSTERS("NUMBER_OF_ESX_CLUSTERS"),
    MAX_NUMBER_OF_CX_ARRAYS("MAX_NUMBER_OF_CX_ARRAYS"),
    MAX_NUMBER_OF_VNX_ARRAYS("MAX_NUMBER_OF_VNX_ARRAYS"),
    MAX_NUMBER_OF_VC_ARRAYS("MAX_NUMBER_OF_VC_ARRAYS"),
    MAX_NUMBER_OF_VPLEX_ARRAYS("MAX_NUMBER_OF_VPLEX_ARRAYS"),
    MAX_NUMBER_OF_XTREME_ARRAYS("MAX_NUMBER_OF_XTREME_ARRAYS"),
    MAX_NUMBER_OF_SCALE_IO_ARRAYS("MAX_NUMBER_OF_SCALE_IO_ARRAYS"),
    MAX_NUMBER_OF_SNAPSHOTS("MAX_NUMBER_OF_SNAPSHOTS"),
    MAX_NUMBER_OF_SNAPSHOT_MOUNT_POINTS("MAX_NUMBER_OF_SNAPSHOT_MOUNT_POINTS"),
    MAX_NUMBER_OF_SNAPSHOTS_PER_DEVICE("MAX_NUMBER_OF_SNAPSHOTS_PER_DEVICE"),
    MAX_NUMBER_OF_DEVICES("MAX_NUMBER_OF_DEVICES"),
    MAX_NUMBER_OF_DEVICES_PER_RESOURCE_POOL("MAX_NUMBER_OF_DEVICES_PER_RESOURCE_POOL"),
    MAX_NUMBER_OF_DEVICES_PER_MASKING_GROUP("MAX_NUMBER_OF_DEVICES_PER_MASKING_GROUP"),
    MAX_NUMBER_OF_MEMBERS_PER_ARRAY_CGS("MAX_NUMBER_OF_MEMBERS_PER_ARRAY_CGS"),
    MAX_NUMBER_OF_ARRAY_CGS("MAX_NUMBER_OF_ARRAY_CGS"),
    MAX_NUMBER_OF_BRICKS("MAX_NUMBER_OF_BRICKS"),
    MAX_DEVICE_SIZE_GB("MAX_DEVICE_SIZE_GB"),
    NUMBER_OF_EXTERNAL_AMPS_PER_CLUSER("NUMBER_OF_EXTERNAL_AMPS_PER_CLUSER"),
    NUMBER_OF_SYMM_V_3_HOSTS("NUMBER_OF_SYMM_V3_HOSTS"),

    NUMBER_OF_VIRTUAL_JOURNALS("NUMBER_OF_VIRTUAL_JOURNALS"),
    NUMBER_OF_ESX_HOSTS_WITH_SPLITTER("NUMBER_OF_ESX_HOSTS_WITH_SPLITTER"),
    NUMBER_OF_PROTECTED_VMS("NUMBER_OF_PROTECTED_VMS"),
    NUMBER_OF_PROTECTED_VMDKS("NUMBER_OF_PROTECTED_VMDKS"),
    NUMBER_OF_SITES("NUMBER_OF_SITES"),
    NUMBER_OF_VMS_PER_GROUP("NUMBER_OF_VMS_PER_GROUP"),
    NUMBER_OF_REPLICA_COPIES_PER_GROUP("NUMBER_OF_REPLICA_COPIES_PER_GROUP"),
    NUMBER_OF_SITES_CONNECTED_TO_VC("NUMBER_OF_SITES_CONNECTED_TO_VC"),
    NUMBER_OF_VMS_PROTECTED_PER_VC("NUMBER_OF_VMS_PROTECTED_PER_VC"),
    UNKNOWN("UNKNOWN");

    private final String value;

    private MonitoredParameterType(String v) {
        this.value = v;
    }

    public static MonitoredParameterType fromValue(String v) {
        for (MonitoredParameterType c : MonitoredParameterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return this.value;
    }
}


